// src/App.vue
<script setup lang="ts">

import '@/styles/all.scss';
import '@/styles/mixins.scss';
import { BaseButton } from './components';

</script>

<template>
  <div class="f-r ga-32 a-start bg-gray-2 pa-64">
    <div class="f-r ga-16">
      <div class="f-c ga-12">
        <h1 class="h-1">Heading 1</h1>
        <h2 class="h-2">Heading 2</h2>
        <h3 class="h-3">Heading 3</h3>
        <h4 class="h-4">Heading 4</h4>
      </div>
      <div class="f-c ga-12">
        <p class="b-1">Body 1</p>
        <p class="b-2">Body 2</p>
        <p class="b-3">Body 3</p>
        <p class="b-4">Body 4</p>
        <p class="b-5">Body 5</p>
        <p class="b-6">Body 6</p>
      </div>
    </div>
    <div class="f-c ga-12">
      <BaseButton color="white">Button</BaseButton>
      <BaseButton color="white-accent">Button</BaseButton>
      <BaseButton color="black">Button</BaseButton>
      <BaseButton color="black-accent">Button</BaseButton>
      <BaseButton color="accent">Button</BaseButton>
      <BaseButton color="accent-alt">Button</BaseButton>
    </div>
    <div class="f-c ga-12">
      <BaseButton outline color="white">Button</BaseButton>
      <BaseButton outline color="white-accent">Button</BaseButton>
      <BaseButton outline color="black">Button</BaseButton>
      <BaseButton outline color="black-accent">Button</BaseButton>
      <BaseButton outline color="accent">Button</BaseButton>
      <BaseButton outline color="accent-alt">Button</BaseButton>
    </div>
  </div>
</template>

<style scoped></style>

// src/app/page.tsx
import { A, Button } from "@/components"

const styles : { [key: string]: React.CSSProperties } = {
  gray: {
    backgroundColor: '#808080'
  }
}

export default function Home() {

  const colors : { 
    [group: string] : {
      name: string, 
      value: string,
      text: string
    }[] } = {
    grays: [
      {
        name: 'white',
        value: '#F2F2F2',
        text: 'black'
      },
      {
        name: 'gray-1',
        value: '#BFBFBF',
        text: 'black'
      },
      {
        name: 'gray-2',
        value: '#797979',
        text: 'white'
      },
      {
        name: 'gray-3',
        value: '#333333',
        text: 'white'
      },
      {
        name: 'black',
        value: '#000000',
        text: 'white'
      }
    ],
    accents: [
      {
        name: 'accent',
        value: '#FF40BF',
        text: 'white'
      },
      {
        name: 'accent-1',
        value: '#FFBFE9',
        text: 'black'
      },
      {
        name: 'accent-2',
        value: '#FF99DD',
        text: 'black'
      },
      {
        name: 'accent-3',
        value: '#660043',
        text: 'white'
      }
    ]
  }

  const texts: {[group:string]: string[]} = {
    headings: [
      'heading-1', 'heading-2', 'heading-3', 'heading-4'
    ],
    bodies: [
      'body-1', 'body-2', 'body-3', 'body-4', 'body-5', 'body-6'
    ]
  }

  const components: string[] = [
    'white', 'black', 'accent', 'accent-alt', 'white-accent', 'black-accent'
  ]

  return (
    <div className="f-rw gap-32 pad-all-32" style={styles.gray}>
      <div className="f-c gap-16">
        <div className="f-r gap-8">
          {colors.grays.map((i) => {
            return(
              <div key={i.value} className={`bg-${i.name} color-${i.text} body-4 pad-all-8 rad-all-8`}>{i.value}</div>
            )
          })}
        </div>
        <div className="f-r gap-8">
          {colors.accents.map((i) => {
            return(
              <div key={i.value} className={`bg-${i.name} color-${i.text} body-4 pad-all-8 rad-all-8`}>{i.value}</div>
            )
          })}
        </div>
      </div>
      <div className="f-c gap-16">
        <div className="f-c gap-8">
          {texts.headings.map((i) => {
            return (
              <div key={i} className={i}>{i}</div>
            )
          })}
        </div>
        <div className="f-c gap-8">
          {texts.bodies.map((i) => {
            return (
              <div key={i} className={i}>{i}</div>
            )
          })}
        </div>
      </div>
      <div className="f-c gap-8">
        {components.map((i) => {
          return (
            <A className="body-4" key={i} color={i}>Link {i}</A>
          )
        })}
      </div>
      <div className="f-c gap-8">
        {components.map((i) => {
          return (
            <Button className="body-4" key={i} color={i}>Button {i}</Button>
          )
        })}
      </div>
    </div>
  );
}
